### ISSUE TITLE
How to reference sample.name in subset from a variable

### ISSUE THREAD

**Issue by daniel-darnell1** [jwfoley/bioanalyzeR#29] opened 2023-01-30 17:03 UTC
Hey! This maybe a very niche request, but I am listing all samples from a TapeStation D1000 file to a table in an R Shiny app ( using library DT). I am grabbing the actively selected sample (selected <- input$tsSamples_rows_selected) and then passing that sample's name to a variable. When I reference that variable in the subset command see code below. I get an error stating object 'sampleName' not found. However, I can print the variable in the line directly above; so I don't think it has anything to do with the variable being unavailable or outside the scope. Any ideas/suggestions? Thank you!

`library("shiny")
library("bioanalyzeR")
library("DT")

shinyServer(function(input, output, session) {

    output$sjUser <- renderText({session$user})
    ts_data <- read.tapestation('www/221214_92_ChIP_287439_DD - 2023-01-10 - 10-39-06-D1000.xml', csv.file = 'www/221214_92_ChIP_287439_DD - 2023-01-10 - 10-39-06-D1000_Electropherogram.csv')
    output$tsSamples <- renderDT(ts_data$samples, selection = "single")
    observe({
      req(input$tsSamples_rows_selected)
      selected <- input$tsSamples_rows_selected
      table1 <- as.data.frame(ts_data$samples$sample.name)
      sampleName <- table1[['ts_data$samples$sample.name']][[selected]]
      print(sampleName)
      filter_sample <- subset(ts_data, startsWith(as.character(sample.name), sampleName))
      #also tried filter_sample <- subset(ts_data, sample.name == sampleName)
      #error for that command is Warning: Error in eval: object 'sampleName' not found
      output$plot <- renderPlot(rawplot.electrophoresis(filter_sample, show.peaks = "all"))
    })
})
`

Output:
> shiny::runApp('RShinyApps/tapeStation')
Loading required package: shiny

Listening on http://127.0.0.1:4392

Attaching package: ‘DT’

The following objects are masked from ‘package:shiny’:

    dataTableOutput, renderDataTable

[1] 2521128_TL47K562BRG1
Warning: Error in startsWith: object 'sampleName' not found
  52: startsWith
  51: eval
  50: eval
  49: subset.data.frame
  47: subset.electrophoresis
  45: observe [C:\Users\ddarnell\Documents\RShinyApps\tapeStation/server.R#16]
  44: <observer>
   1: shiny::runApp
[D1000 Files.zip](https://github.com/jwfoley/bioanalyzeR/files/10538093/D1000.Files.zip)

**Comment by jwfoley** [comment] 2023-01-31 18:54
Unfortunately I'm not very familiar with Shiny so I don't know how to reproduce this, but if I understand correctly you want to do something like this, which works:

    library(bioanalyzeR)
    sampleName <- "2527"
    ts_data <- read.tapestation("221214_92_ChIP_287439_DD - 2023-01-10 - 10-39-06-D1000.xml")
    filter_sample <- subset(ts_data, startsWith(as.character(sample.name), sampleName))
    qplot.electrophoresis(filter_sample)

but wrap it inside a Shiny session, which doesn't work. It seems like the problem is coming from your invocation of Shiny - `subset()` can't find sampleName defined in that scope, even though you just defined it right there and `print()` can find it. I'm not sure what's going on there. What if you try

    test <- subset(ts_data$samples, startsWith(as.character(sample.name), sampleName))
    print(test)

to diagnose it? If that works then maybe the problem is specifically with `subset.electrophoresis()`; if not it's more general to `subset.data.frame()`. I have a feeling it could be something about how `subset.data.frame()` looks for variable names inside the data frame's scope (how it finds `sample.name`), but I'm not sure why it would behave differently inside `observe()` vs. outside it.

**Comment by daniel-darnell1** [comment] 2023-02-01 23:46
Hey @jwfoley! Thanks for your help and suggestions. I finally figured out a way to make this work.

 I'm sure it's not the most elegant. But if I store the full subset command into a variable and then evaluate that variable to actually perform the subset, it works as intended. Feel free to close this issue, or I can if you want?

I am creating this R Shiny app for our department to use (essentially creating a GUI wrapper to mimic TapeStation software.) As a user selects a sample in the table, the plot reactively updates to display that sample.

Full code below:
`library("shiny")
library("bioanalyzeR")
library("DT")
library("tidyverse")

shinyServer(function(input, output, session) {

    output$sjUser <- renderText({session$user})
    ts_data <- read.tapestation('www/221214_92_ChIP_287439_DD - 2023-01-10 - 10-39-06-D1000.xml', csv.file = 'www/221214_92_ChIP_287439_DD - 2023-01-10 - 10-39-06-D1000_Electropherogram.csv')
    output$tsSamples <- renderDT(subset(ts_data$samples, sample.name != "Ladder"), selection = "single")
    output$tsRegions <- renderDT(ts_data$regions, selection = "none")
    observeEvent(input$tsSamples_rows_selected, {
      selected <- input$tsSamples_rows_selected
      table1 <- data.frame(ts_data$samples$sample.name)
      sampleName <- as.character(table1[selected, ])
      filter_sample <- expr(subset(ts_data, sample.name == !!sampleName))
      ts_data_subset <- eval(filter_sample)
      output$plot <- renderPlot(rawplot.electrophoresis(ts_data_subset, show.peaks = "all"))
    })
})
`

**Comment by jwfoley** [comment] 2023-02-02 02:38
I'm glad you found a workaround, but I'm still curious about the problem. It does seem like a name-scoping thing but maybe not how I first guessed. What if instead of asking for `subset(ts_data)` you ask for `subset.electrophoresis(ts_data)`? I wonder if `observeEvent()` is actually losing the `subset.electrophoresis()` function (which `subset()` is supposed to point to) so it's trying to use `subset.default()` instead. Maybe if you spell out the whole name it will work normally.

**Comment by daniel-darnell1** [comment] 2023-02-02 17:33
Hey! You were absolutely correct. When I call `subset.electrophoresis(ts_data)` within `observeEvent()` I get the following error: Warning: Error in subset.electrophoresis: could not find function "subset.electrophoresis".

**Comment by jwfoley** [comment] 2023-02-02 19:46
OK, I'll close this issue since it doesn't seem like the problem is with bioanalyzeR, but I'd encourage you to look for support with Shiny (try Stack Exchange?) to figure out what is really going on here. The problem seems to be that you can't find the `subset.electrophoresis()` function from inside `observeEvent()`, even though you can find `rawplot.electrophoresis()`, and even though it shows up if you wrap it inside `expr()`. So there's something weird about how functions are found inside `observeEvent()`.

If you do follow up on that and it turns out there's something to fix in bioanalyzeR that would solve this, please come back and let me know.

**Closed by jwfoley** 2023-02-02 19:46 UTC
